---
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: cvwonder-studio:dev
    container_name: cvwonder-studio
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://cvwonder:cvwonder@database:5432/cvwonder
    
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: cvwonder
      POSTGRES_PASSWORD: cvwonder
      POSTGRES_DB: cvwonder
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
