{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cvwonder-studio.fullname" . }}
  namespace: {{ .Values.forceNamespace | default .Release.Namespace }}
  labels:
    {{- include "cvwonder-studio.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cvwonder-studio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
