{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cvwonder-studio.fullname" . }}
  namespace: {{ .Values.forceNamespace | default .Release.Namespace }}
  labels:
    {{- include "cvwonder-studio.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  user-token-secret: {{ .Values.secrets.userTokenSecret | quote }}
  admin-username: {{ .Values.secrets.adminUsername | quote }}
  admin-password-hash: {{ .Values.secrets.adminPasswordHash | quote }}
  admin-token-secret: {{ .Values.secrets.adminTokenSecret | quote }}
  google-client-id: {{ .Values.secrets.googleClientId | quote }}
  google-client-secret: {{ .Values.secrets.googleClientSecret | quote }}
{{- end }}
